//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.

public class Problem2 {
	public static void main(String[] args) {
		int atual = 1;
		int anterior = 1;
		int limit =0;
		int sum =0;
		while (true){	
			limit = atual + anterior;
			anterior = atual ;
			atual = limit;
			if (limit > 4000000){
				break;
			}
			if (limit % 2 == 0)
				sum += limit;
		}
		System.out.println(sum);
	}

}


